ShootShot/ViewModels/CProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.WebPages.Html;

namespace ShootShot.ViewModels
{
	public class CProjectViewModel
	{
		public CProjectViewModel()
		{
			this.project = new tProject();
			this.member = new tMember();
			//this.memberphoto= new tMemberPhot();
			//this.SelectListItem= new SelectListItem();
		}
		//public SelectListItem SelectListItem { get; set; }
		//public string fEmail
		//{
		//	get { return this.memberphoto.fEmail; }
		//	set { this.SelectListItem.Value = value; }
		//}
		//public string fName
		//{
		//	get { return this.memberphoto.fName; }
		//	set { this.SelectListItem.Text = value; }
		//}
		public tProject project { get; set; }
		public tMember member { get; set; }
		//public tMemberPhot memberphoto { get; set; }
		public int fId
		{
			get { return this.project.fId; }
			set { this.project.fId = value; }
		}
		[DisplayName("專案訂單編號")]
		public string fOrderNum
		{
			get { return this.project.fOrderNum; }
			set { this.project.fOrderNum = value; }
		}
		[DisplayName("專案成立日期")]
		public Nullable<System.DateTime> fPjtDate {
			get {return this.project.fPjtDate; }
			set {this.project.fPjtDate=value; } 
		}
		[DisplayName("一般會員Email")]
		public string fCEmail
		{
			get { return this.project.fCEmail; }
			set { this.project.fCEmail = value; }
		}
		// 藉由fCEmail傳回電話姓名
		//public string fCName {
		//	get { return this.member.fName; }
		//	set { }
		//}
		//public string fCName { get; set; }
		//public string fCTel { get; set; }

		[DisplayName("專案聯繫人")]
		public string fContact
		{
			get { return this.project.fContact; }
			set { this.project.fContact = value; }
		}
		[DisplayName("專案聯繫人電話")]
		public string fContactTel
		{
			get { return this.project.fContactTel; }
			set { this.project.fContactTel = value; }
		}
		[DisplayName("平日可聯繫時間")]
		public string fWkdyTime
		{
			get { return this.project.fWkdyTime; }
			set { this.project.fWkdyTime = value; }
		}
		[DisplayName("假日可聯繫時間")]
		public string fWkndTime
		{
			get { return this.project.fWkndTime; }
			set { this.project.fWkndTime = value; }
		}
		[DisplayName("拍攝城市")]
		public string fCity
		{
			get { return this.project.fCity; }
			set { this.project.fCity = value; }
		}
		[DisplayName("拍攝地點")]
		public string fLoc
		{
			get { return this.project.fLoc; }
			set { this.project.fLoc = value; }
		}
		[DisplayName("拍攝日期")]
		public Nullable<System.DateTime> fFilmDate
		{
			get { return this.project.fFilmDate; }
			set { this.project.fFilmDate = value; }
		}
		[DisplayName("拍攝時間")]
		public Nullable<System.TimeSpan> fFilmTime
		{
			get { return this.project.fFilmTime; }
			set { this.project.fFilmTime = value; }
		}
		[DisplayName("拍攝預算")]
		public Nullable<int> fBudget
		{
			get { return this.project.fBudget; }
			set { this.project.fBudget = value; }
		}
		[DisplayName("出圖張數")]
		public Nullable<int> fPrintQty
		{
			get { return this.project.fPrintQty; }
			set { this.project.fPrintQty = value; }
		}
		[DisplayName("專案主題")]
		public string fPjtTopic
		{
			get { return this.project.fPjtTopic; }
			set { this.project.fPjtTopic = value; }
		}
		[DisplayName("專案需求")]
		public string fReq
		{
			get { return this.project.fReq; }
			set { this.project.fReq = value; }
		}





		[DisplayName("參考風格")]
		public string fStyle
		{
			get { return this.project.fStyle; }
			set { this.project.fStyle = value; }
		}
		[DisplayName("專案狀態")]
		public Nullable<bool> fPjtState
		{
			get { return this.project.fPjtState; }
			set { this.project.fPjtState = value; }
		}
		//public string fPName { get; set; }
		//public string fEmail
		//{
		//	get { return this.member.fEmail; }
	
		//}
		[DisplayName("攝影師Email")]
		public string fPEmail
		{
			get { return this.member.fEmail; }
			set { this.project.fPEmail = value; }
		}
		[DisplayName("參考照片")]
		public string fPicUpload
		{
			get { return this.project.fPicUpload; }
			set { this.project.fPicUpload = value; }
		}
		public HttpPostedFileBase photo { get; set; }
	}
}

ShootShot/Controllers/CProjectController.cs
using Azure.Core;
using Grpc.Core;
using ShootShot.Models;
using ShootShot.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages.Html;
using SelectListItem = System.Web.WebPages.Html.SelectListItem;

namespace ShootShot.Controllers
{
	public class CProjectController : Controller
    {
        // GET: CProject
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Create()
        {
            dbShootShotEntities db = new dbShootShotEntities();



			// 判斷身分
			if (Session[Dictionary.USER_ID] == null)
			{
				return RedirectToAction("Login", "LoginAndSignup");
			}


			//tMember photog = new tMember();

			int id = (int)Session[Dictionary.USER_ID];
			var member = db.tMember.Where(t => t.fId == id).FirstOrDefault();
            string cemail = member.fEmail.ToString();
            tMember cust = db.tMember.FirstOrDefault(m => m.fEmail == cemail);

            if (cust != null)
            {
                ViewBag.txtCEmail = cemail;
                ViewBag.txtCTel = cust.fTel;
                ViewBag.txtCName = cust.fName;
            };
            //int code = 1;
            //tMember photog = from g in db.tMember where g.fCode == code select new { g.fEmail,g.fName};

            // 匯入攝影師資訊
            ////	var photogs = from m in db.tMember where m.fCode.Equals(1) orderby m.fId select m;
            ////	var photogs = db.tMember.Where(m => m.fCode.Equals(1)).OrderBy(m => m.fId).ToString();
            ////	List<SelectList> photogs = new List<SelectList>()
            ////	{
            ////		ViewBag.PhotogList = new SelectList(
            ////		items: photogs,
            ////		dataTextField: "fName",
            ////		dataValueField: "fEmail"
            ////		);
            ////};
            //var x = 1;
            //var photos = from m in db.tMember where m.fCode.Equals(x) orderby m.fId select m;
            //List<SelectList> items = new List<SelectList>();
            //foreach (var photo in photos)
            //{
            //    items.Add(new SelectList()
            //    {
            //        DataTextField = photo.fName.ToString(),
            //        DataValueField = photo.fEmail

            //    });
            //    //    // 攝影師連結直接選定攝影師
            //    //    //items.Where(q => q.Value == cemail).First().Selected = true;
            //    //}
            //    ViewBag.PhotoItems = items;
            //}

    //        var selectList = new List<System.Web.Mvc.SelectListItem>()
    //        {
    //            new System.Web.Mvc.SelectListItem {Text="text-1", Value="value-1" },
    //            new System.Web.Mvc.SelectListItem {Text="text-2", Value="value-2" },
				//new System.Web.Mvc.SelectListItem {Text="text-3", Value="value-3" },
    //        };

    //        //預設選擇哪一筆
    //        selectList.Where(q => q.Value == "value-2").First().Selected = true;

    //        ViewBag.SelectList = selectList;

            return View();

        }
        // POST: CProject/Create
        [HttpPost]
		public ActionResult Create(CProjectViewModel p)
        {
			string photoName = Guid.NewGuid().ToString() + ".jpg";
			// 錯誤訊息,未將物件設定參考=>action要設定photo再由controller這邊存路徑
			p.photo.SaveAs(Server.MapPath("~/Content/") + photoName);
			p.fPicUpload = "/" + photoName;
			// 訂單編號
			Random rnd = new Random();
            int x = rnd.Next(10, 99);
            p.fOrderNum = DateTime.Now.ToString("yyyyMMdd") + x.ToString();
            p.fPEmail = Request.Form["txtPEmail"];
            dbShootShotEntities db = new dbShootShotEntities();
            db.tProject.Add(p.project);
            db.SaveChanges();
		    ModelState.Clear();
            return View();

        }

    }
}

ShootShot/Views/CProject/Create.cshtml
@model ShootShot.ViewModels.CProjectViewModel
@using SelectListItem = System.Web.Mvc.SelectListItem;
@{
	ViewBag.Title = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
	//List<SelectListItem> list = ViewBag.List;
}

<main>
	<section class="cProject_sec1">
		<div>
			<img src="~/Content/img/預約專案形象圖.png" />
		</div>
		<div class="filter">

		</div>
	</section>
	<section>
		@using (Html.BeginForm("Create", "CProject", FormMethod.Post, new { enctype = "multipart/form-data" }))
		{
			@Html.AntiForgeryToken()
			<form>
				<div class="cProject_conForform1">
					<div class="row">
						<!-- 預約您的專案．．．．．．文字位置調整 -->
						<div class="col-md-6 formbar_container">
							<label id="cProject_lblForalink1"
								   class="cProject_lblFortxt1" style="margin-left: 200px;" for="">預約您的專案．．．．．．</label>
						</div>

						<!-- 攝影師姓名即Email由資料庫帶入,亦打關鍵字找人 -->
						<div class="col-md-6 formbar_container" style="padding-right: 400px">
							<label for="cProject_txtId1" class="cProject_lblFortxt1" ;>您所預約攝影師為：</label>

							@*未完成*@
							@*@Html.DropDownList("List");*@
							@*@Html.DropDownListFor(m => m.fPEmail, new SelectList(Model.fPEmail,"Value", "Text"),new { name="txtPEmail"})*@
							@*@Html.DropDownList("items", (SelectList)ViewBag.PhotogList, new { @id= "PhotogList" })*@
							@*@Html.TextBoxFor(m => m.fPEmail, new { @class = "cProject_lblFortxt1", id = "txtPEmail", name = "txtPEmail" })*@
						<select class="cProject_lblFortxt1" name="txtPEmail" id="txtPEmail" required>
							<option value="">請選擇攝影師</option>
							<option value="mikhail1974@gmail.com">Nilov</option>
							<option value="lucas1976@gmail.com">Pezeta</option>
							<option value="olga1986@gmail.com">Olga Dimenshtein</option>
						</select>

						</div>
						@{
							Random rnd = new Random();
							int x = rnd.Next(10, 99);
							var x_ = DateTime.Now.ToString("yyyyMMdd") + x.ToString();
							var x1_ = DateTime.Now;
						}
						@Html.TextBoxFor(m => m.fOrderNum, new { type = "hidden", @Value = x_ })
						@Html.TextBoxFor(m => m.fPjtDate, new { type = "hidden", @Value = x1_ })
					</div>
				</div>
				<div class="cProject_conForform2">
					<div class="container">
						<div class="row">
							<div class="col-md-3">
								<div class="cProject_btn2">
									<a class="cProject_alink1 active" href="#cProject_conForform1">
										<label class="cProject_lbl1" for="cProject_alink2">step1</label>
										<label class="cProject_lbl2" for="cProject_alink2">用戶資料</label>
									</a>
								</div>
								<br />
								<div class="cProject_btn2">
									<a class="cProject_alink1" href="#cProject_conForformId2">
										<label class="cProject_lbl1" for="cProject_alink2">step2</label>
										<label class="cProject_lbl2" for="cProject_alink2">專案內容</label>
									</a>
								</div>
								<br />
							</div>
							@*container-right用戶資料表單;這邊要用前端數據帶入後建立專案再寫入資料庫;所以要建立name?????*@
							<div class="col-md-9">
								<div id="cProject_conForformId1">
									<div>
										<h3 for="">開始創建我的專案</h3>
									</div>
									<div class=" row">
										<div class="col">
											@Html.TextBox("姓名", null, new { @class = "cProject_txt1", @readonly = "true", Type = "text", name = "txtCName", @Value = ViewBag.txtCName })
										</div>
										<div class="col">
											@Html.TextBox("電話", null, new { @class = "cProject_txt1", @readonly = "true", Type = "tel", name = "txtCTel", @Value = ViewBag.txtCTel })
										</div>
									</div>
									<div>
										@Html.TextBoxFor(m => m.fCEmail, new { @class = "form-control", @readonly = "true", Type = "email", name = "txtCEmail", @Value = ViewBag.txtCEmail })
									</div>
									<br />
									<br />
									<div>
										<h3 class="formLab">專案創建後，將由攝影師與您聯繫，請提供方便與您聯繫的時間與聯絡電話</h3>
									</div>
									<div class=" row">
										<div class="col">
											@Html.TextBoxFor(m => m.fContact, new { @class = "cProject_txt1", placeholder = "指定聯絡人", required = "required" })
										</div>
										<div class="col">
											@Html.TextBoxFor(m => m.fContactTel, new { @class = "cProject_txt1", placeholder = "聯絡人電話", required = "required" })
										</div>
									</div>
									<br />
									<br />
									<div>
										<h3 class="formLab">可聯繫時間</h3>
									</div>
									<div class=" row">
										<div class="col">
											@*用前端語法勾選後input才可填寫*@
											<div class="form-check">
												<h6 class="form-check-label" for="flexCheckIndeterminate">
													平日 (週一至週五)
												</h6>
											</div>
											@Html.TextBoxFor(m => m.fWkdyTime, null, new { @class = "form-control", placeholder = "請填寫24小時制方便聯繫時間;如填寫14~17," })
										</div>
										<div class="col">
											<div class="form-check">
												<h6 class="form-check-label" for="flexCheckIndeterminate">
													假日 (每週六日及國定假日)
												</h6>
											</div>
											@Html.TextBoxFor(m => m.fWkndTime, null, new { @class = "form-control", placeholder = " 攝影師將於假日下午2~5點與您聯繫" })
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="cProject_conForform3">
					<div class="container">
						<div class="row">
							<div class="col-md-3">
								<div class="cProject_btn2">
									<a class="cProject_alink1" href="#cProject_conForformId1">
										<label class="cProject_lbl1" for="cProject_alink2">step1</label>
										<label class="cProject_lbl2" for="cProject_alink2">用戶資料</label>
									</a>
								</div>
								<br />
								<div class="cProject_btn2">
									<a class="cProject_alink1" href="#cProject_conForformId2">
										<label class="cProject_lbl1" for="cProject_alink2">step2</label>
										<label class="cProject_lbl2" for="cProject_alink2">專案內容</label>
									</a>
								</div>
								<br />
							</div>
							<div class="col-md-9">
								<div id="cProject_conForformId2">
									<div>
										<h3 class="formLab" for="">專案內容與拍攝細節</h3>
									</div>
									<div class=" row">
										<div class="col">
											@*資料庫要帶入*@
											@Html.TextBoxFor(m => m.fCity, null, new { @class = "cProject_txt2", placeholder = "拍攝城市", id = "city", name = "txtCity", required = "required" })
										</div>
										<div class="col">
											@Html.TextBoxFor(m => m.fLoc, null, new { @class = "cProject_txt2", placeholder = "拍攝地點", id = "Loc", name = "txtLoc", required = "required" })
										</div>
									</div>
									<div class=" row">
										<div class="col">
											@Html.TextBoxFor(m => m.fFilmDate, null, new { @class = "cProject_txt2", placeholder = "拍攝日期", type = "date", name = "txtFilmDate", required = "required" })
										</div>
										<div class="col">
											@Html.TextBoxFor(m => m.fFilmTime, null, new { @class = "cProject_txt2", placeholder = "拍攝時間", type = "time", name = "txtFilmTime", required = "required" })
										</div>
									</div>
									<div class=" row">
										<div class="col">
											@Html.TextBoxFor(m => m.fBudget, null, new { @class = "cProject_txt2", placeholder = "我的預算", type = "number", name = "txtBudget", min = "1", required = "required" })
										</div>
										<div class="col">
											@Html.TextBoxFor(m => m.fPrintQty, null, new { @class = "cProject_txt2", placeholder = "出圖張數", type = "number", name = "txtPrintQty", min = "1", max = "20", required = "required" })
										</div>
									</div>
									<div>
										<h3 for="">讓攝影師更了解您想拍攝的專案吧！</h3>
									</div>
									<div class="row">
										@Html.TextBoxFor(m => m.fPjtState, new { type = "hidden", @Value = false })
										@Html.TextBoxFor(m => m.fPjtTopic, null, new { @class = "cProject_txt3", placeholder = "專案主題", type = "text", id = "prjName", name = "txtPjtTopic", required = "required", style = "margin: 0.5rem auto; width: 96%;border: none;font-size: 1rem;padding: 10px 15px 10px 15px;border-radius: 8px;outline: none;" })
									</div>
									<div class="row">
										<div class="col-md-6">
											@Html.TextAreaFor(m => m.fReq, new { @class = "cProject_txtbox1 cProject_txt2", placeholder = "需求描述(協助攝影師更加精準掌握您的需求)# 室內# 戶外# 網路用途# 電商用途# 個人收藏# 印刷用途", name = "txtReq", required = "required", style = "margin: 0.5rem auto; width: 100%;border: none;font-size: 1rem;padding: 10px 15px 10px 15px;border-radius: 8px;outline: none;height:20vh" })
										</div>
										<div class="col-md-6">
											@Html.TextBoxFor(m => m.fStyle, null, new { @class = "cProject_url1 cProject_txt2", placeholder = "風格參考（請提供參考網址）", id = "style", name = "txtStyle", type = "url", style = "margin: 0.5rem auto; width: 100%;border: none;font-size: 1rem;padding: 10px 15px 10px 15px;border-radius: 8px;outline: none;" })
											<div class="conForpic1"style="margin: 0.5rem auto; width: 100%;border: none;font-size: 1rem;padding: 10px 15px 10px 15px;border-radius: 8px;outline: none;background-color:white;color:#242424">						
												<input id="picUpload" type="file" name="photo" class="" accept="image/gif,image/jpeg,image/png"/>
												<img id="previewPicUpload" src="" />
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				<!-- 表格傳送資料按鈕 -->
				<div class="submitForm_container">

					<button type="submit" class="btn_submit" style="font-size:1.8rem; color:#242424;">
						@*<img src="/project/img/SVG/contact-form.svg" alt="">*@
						 建立專案
					</button>
				</div>
			</form>}
	</section>
</main>

@*<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
	$(document).ready(function () {
		$('#PhotogList').change(function () {
			alert($('#PhotogList').val());
		});
	})
</script>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
	$(document).ready(function () {
		$('#selector').change(function () {
			alert($('#selector').val());
		});
	})
</script>*@

@*@section Scripts {
		@Scripts.Render("~/bundles/jqueryval")
	}*@

ShootShot/Views/CProject/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<body>

	<!-- #region 妳的html -->
	<main>
		<!-- 形象圖片start -->
		<section class="cProject_sec1">
			<div>
				<img src="~/Content/images/預約專案形象圖.png" />
			</div>
			<div class="filter">

			</div>
			<a href="#cProject_lblForalink1">@Html.ActionLink(">>建立您的專案", "Login", "Home")</a>
		</section>
		<!-- 形象圖片End -->
		<!-- 表單區域start -->


	</main>



	<!-- endregion -->
	<!-- #region backToUp請勿更改 -->
	<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
	<!-- $endregion -->
	<!-- #region js請勿更改 -->
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
	<script src="lib/easing/easing.min.js"></script>
	<script src="lib/owlcarousel/owl.carousel.min.js"></script>
	<script src="lib/isotope/isotope.pkgd.min.js"></script>
	<script src="lib/lightbox/js/lightbox.min.js"></script>
	<script src="mail/jqBootstrapValidation.min.js"></script>
	<script src="mail/contact.js"></script>
	<script src="js/main.js"></script>
	<!-- #endregion -->
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")

</body>
</html>