ShootShot/Controllers/PhoPrjMgmtController.cs
using ShootShot.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages.Html;

namespace ShootShot.Controllers
{
    public class PhoPrjMgmtController : Controller
    {
        // GET: PhoPrjMgmt
        public ActionResult List()
        {
            dbShootShotEntities db = new dbShootShotEntities();

            IEnumerable<tProject> projects = null;
            ;
            int id = 7;
            //int id = (int)Session[Dictionary.USER_ID];
            var member = db.tMember.Where(t => t.fId == id & t.fCode == 1).FirstOrDefault();
            string pemail = member.fEmail.ToString();
            // 攝影師註冊登入照片
            var PtMember = db.tMember.Where(m => m.fEmail == pemail).FirstOrDefault()?.fPhoto ?? "user.png";
            if (!string.IsNullOrEmpty(PtMember))
                TempData["PhoImg"] = PtMember.ToString();
            // 選擇攝影師所有專案匯入
            projects = from p in db.tProject where p.fPEmail.Contains(pemail) select p;
            MProjectViewModel prj = new MProjectViewModel();
            prj.projects = projects;
            // 接收查詢專案訂單編號
            string OrderNo = Request.Form["txtOrderNum"];
            // 客戶註冊登入照片
            string CfEmail = (from p in db.tProject where p.fOrderNum == OrderNo select new { p.fCEmail }).ToString();
            var CtMember = db.tMember.Where(m => m.fEmail == CfEmail).FirstOrDefault()?.fPhoto ?? "user.png";
            if (!string.IsNullOrEmpty(CtMember))
                TempData["CustImg"] = CtMember.ToString();
            // 列出查詢專案詳細資訊
            if (string.IsNullOrEmpty(OrderNo))
            {
                // 不列出
            }
            else
            {
                // 專案詳細訊息
                tProject tprj = db.tProject.FirstOrDefault(m => m.fOrderNum == OrderNo);
                var tPrj = db.tProject.Where(t => t.fOrderNum == OrderNo).FirstOrDefault();
                var tMember = db.tMember.Where(t => t.fEmail == tPrj.fPEmail).FirstOrDefault();
                string name = tMember.fName.ToString(); ;
                TempData["OrderNum"] = OrderNo;
                TempData["PjtTopic"] = tprj.fPjtTopic;
                TempData["PjtDate"] = tprj.fPjtDate;
                TempData["FilmDate"] = tprj.fFilmDate;
                TempData["FilmTime"] = tprj.fFilmTime;
                TempData["City"] = tprj.fCity;
                TempData["Loc"] = tprj.fLoc;
                TempData["PrintQty"] = tprj.fPrintQty;
                TempData["Budget"] = tprj.fBudget;
                TempData["Style"] = tprj.fStyle;
                TempData["Contact"] = tprj.fContact;
                TempData["ContactTel"] = tprj.fContactTel;
                TempData["WkdyTime"] = tprj.fWkdyTime;
                TempData["WkndTime"] = tprj.fWkndTime;
                TempData["Req"] = tprj.fReq;
                TempData["PicUpload"] = "未上傳照片.png";
                TempData["PhotoName"] = name;
                TempData["PEnail"] = pemail;
                if (!string.IsNullOrEmpty(tprj.fPicUpload))
                {
                    TempData["PicUpload"] = tprj.fPicUpload.ToString();
                }
            }
            return View(prj);
        }
        public ActionResult Create()
        {
            string MsgId = Request.Form["textkey"];
            TempData["fixkey"] = MsgId;
            return View();
        }



        [HttpPost]
        public ActionResult Create(tMsg g)
        {
            dbShootShotEntities db = new dbShootShotEntities();
            int id = 7;
            //	//int id = (int)Session[Dictionary.USER_ID];
            var member = db.tMember.Where(t => t.fId == id & t.fCode == 1).FirstOrDefault();

            string pemail = member.fEmail.ToString();
            string MsgId = Request.Form["textkey"];
            string OrderNo = Request.Form["msgOrderNo"];
            var tPrj = db.tProject.Where(t => t.fOrderNum == OrderNo).FirstOrDefault();
            var tMember = db.tMember.Where(t => t.fEmail == tPrj.fCEmail).FirstOrDefault();
            string cemail = tMember.fEmail.ToString();

            //string key = Request.Form["replyid"];
            //int ikey = Convert.ToInt32(key);
            //tMsg msg = db.tMsg.FirstOrDefault(m => m.fId == ikey);
            //if (msg != null)
            //{
            //    g.fPMsg = Request.Form["phoPrjMgmt_texboxChat"];
            //    msg.fPMsg = g.fPMsg;
            //    msg.fPMsgTime = DateTime.Now;
            //    db.SaveChanges();
            //}
            //else
            //{

                g.fOrderNum = Request.Form["msgOrderNo"];
                g.fPMsg = Request.Form["phoPrjMgmt_texboxChat"];
                g.fPMsgTime = DateTime.Now;
                g.fPEmail = pemail;
                g.fCEmail = cemail;
                g.fStates = false;

                db.tMsg.Add(g);
                //try { 
                db.SaveChanges();
                //} 
                //catch (Exception ex){ throw; }	
            //}
            return RedirectToAction("List");
        }

        // 把replymsg create 寫成if 

        public ActionResult ReplyCustMsg(int id)
        {
            dbShootShotEntities db = new dbShootShotEntities();
           tMsg msgs = null;
            msgs = db.tMsg.Where(g=>g.fId==id).FirstOrDefault();
            MProjectViewModel msg = new MProjectViewModel();
            msg.msg = msgs;
            if (msgs == null)
                return RedirectToAction("List");
            return View(msg);
        }
        [HttpPost]
        public ActionResult ReplyCustMsg(tMsg m)
        {
			dbShootShotEntities db = new dbShootShotEntities();
            tMsg msgs = null;
            msgs = db.tMsg.Where(g => g.fId == m.fId).FirstOrDefault();
            MProjectViewModel msg = new MProjectViewModel();
            msg.msg = msgs;
            if (msgs != null)
            {
                msgs.fPMsg = Request.Form["fPMsg"];
                msgs.fPMsgTime = DateTime.Now;
                msgs.fStates = true;
                db.SaveChanges();
            }

            return RedirectToAction("List");
		}

        public ActionResult _PhoMsgPartial()
        {
            string OrderNo = Request.Form["txtOrderNum"];
            dbShootShotEntities db = new dbShootShotEntities();
            int id = 7;
            var member = db.tMember.Where(t => t.fId == id & t.fCode == 1).FirstOrDefault();
            string pemail = member.fEmail.ToString();

            // 攝影師註冊登入照片
            var PtMember = db.tMember.Where(m => m.fEmail == pemail).FirstOrDefault()?.fPhoto ?? "user.png";
            if (!string.IsNullOrEmpty(PtMember))
                TempData["PhoImg"] = PtMember.ToString();

            // 客戶註冊登入照片
            string CfEmail = (from prj in db.tProject where prj.fOrderNum == OrderNo select new { prj.fCEmail }).ToString();
            var CtMember = db.tMember.Where(m => m.fEmail == CfEmail).FirstOrDefault()?.fPhoto ?? "user.png";
            if (!string.IsNullOrEmpty(CtMember))
                TempData["CustImg"] = CtMember.ToString();
            IEnumerable<tMsg> Msg = null;
            Msg = from g in db.tMsg where g.fOrderNum.Contains(OrderNo) orderby g.fId select g;
            string msg = Msg.ToString();

            return PartialView(Msg);
        }

    }
}

ShootShot/Views/PhoPrjMgmt/List.cshtml
@model ShootShot.ViewModels.MProjectViewModel
@Styles.Render("~/Content/css/phoPrjMgmt.css")
@{
	ViewBag.Title = "List";
	ViewBag.Title = "Create";
	Layout = "~/Views/Shared/_LayoutForPhotoPrj.cshtml";
	ViewBag.Title = "ReplyCustMsg";

}

<!--------------------------------------------------->
<!-- #article 右側欄內容：專案卡片carousel效果 start -->
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">

	<!------------------------------------->
	<!-- #article 右側欄內容：滑動頁面按鈕 -->
	<div class="carousel-indicators phoPrjMgmt_divForslide">
		<button id="phoPrjMgmt_btnForslide1" name="phoPrjMgmt_btnForslide1" type="button"
				data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true"
				aria-label="Slide 1"></button>
		<button id="phoPrjMgmt_btnForslide2" name="phoPrjMgmt_btnForslide2" type="button"
				data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
	</div>

	<!------------------------------------------------>
	<!-- #article 右側欄內容：卡片區塊slide區塊 start -->
	<div class="carousel-inner phoPrjMgmt_divForCard">
		<!-- #article 右側欄內容：卡片區塊slide1 -->
		<div class="carousel-item active" data-bs-interval="10000">
			<!-- #article 右側欄內容：卡片1-1 -->
			@foreach (var item in Model.projects.Take(3))
			{
				string photo = item.fPicUpload;
				<div id="phoPrjMgmt_divForCard1" name="phoPrjMgmt_divForCard1" class="card">
					<img id="phoPrjMgmt_imgCard1" name="phoPrjMgmt_imgCard1" src="~/Content/@photo" class="card-img-top"
						 alt="...">
					<div class="card-body">
						<h5 id="phoPrjMgmt_hCard1" name="phoPrjMgmt_hCard1" class="card-title">@item.fPjtTopic</h5>
						<p id="phoPrjMgmt_pCard1" name="phoPrjMgmt_pCard1" class="card-text">
							建立日期:@item.fPjtDate.ToString().Substring(0, 10)<br>
							指定聯絡人:@item.fContact
						</p>
						@using (Html.BeginForm())
						{
							<input type="hidden" value="@item.fOrderNum" name="txtOrderNum" for="msgOrderNo"><input type="submit" value="前往專案訊息" style="border-radius: 20px; margin: 0px 50px; width: 100px; height: 30px; font-size: 12px; background-color: #7dffd1; border: none; color: #242424;">
						}
					</div>
				</div>
			}
		</div>

		<!-- #article 右側欄內容：卡片區塊slide2 -->
		<div class="carousel-item" data-bs-interval="2000">
			@foreach (var item in Model.projects.Skip(3))
			{
				string photo = item.fPicUpload;
				@*<input type="hidden" name="txtpemail" value="@item.fCEmail" />*@
				<div id="phoPrjMgmt_divForCard4" name="phoPrjMgmt_divForCard4" class="card">
					<img src="~/Content/@photo" class="card-img-top" alt="...">
					<div class="card-body">
						<h5 id="phoPrjMgmt_hCard4" name="phoPrjMgmt_hCard4" class="card-title">@item.fPjtTopic</h5>
						<p id="phoPrjMgmt_pCard4" name="phoPrjMgmt_pCard4" class="card-text">
							建立日期:@item.fPjtDate.ToString().Substring(0, 10)<br>
							指定聯絡人:@item.fContact
						</p>
						@using (Html.BeginForm())
						{
							<input type="hidden" value="@item.fOrderNum" name="txtOrderNum" for="msgOrderNo"><input type="submit" value="前往專案訊息" style="border-radius: 20px; margin: 0px 50px; width: 100px; height: 30px; font-size: 12px; background-color: #7dffd1; border: none; color: #242424;">
						}
					</div>
				</div>
			}
		</div>
	</div>
	<!-- #article 右側欄內容：卡片區塊slide區塊end -->
	<!--------------------------------------------->
	<!-------------------------------------------->
	<!-- #article 右側欄內容：卡片區塊arrow start -->
	<div class="phoPrjMgmt_divForArrow">
		<button id="phoPrjMgmt_btnForPrev" name="phoPrjMgmt_btnForPrev" class="carousel-control-prev" type="button"
				data-bs-target="#carouselExampleDark" data-bs-slide="prev">
			<span><img src="~/Content/img/left_arrows.svg" alt=""></span>
			<span class="visually-hidden"></span>
		</button>
		<button id="phoPrjMgmt_btnForNext" name="phoPrjMgmt_btnForNext" class="carousel-control-next" type="button"
				data-bs-target="#carouselExampleDark" data-bs-slide="next">
			<span><img src="~/Content/img/double-right-arrows.svg" alt=""></span>
			<span class="visually-hidden"></span>
		</button>
	</div>
	<!-- #article 右側欄內容：卡片區塊arrow end -->
	<!------------------------------------------>


</div>
<!-- #article 右側欄內容：專案卡片carousel效果 end -->
<!------------------------------------------------->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
		integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
</script>

<!----------------------------------->
<!-- #article 右側欄內容：專案內容區塊 -->
<div id="phoPrjMgmt_divForMain" name="phoPrjMgmt_divForMain" class="phoPrjMgmt_divForMain">
	<div class="container">
		<div class="project">
			<p id="phoPrjMgmt_pTitle" name="phoPrjMgmt_pTitle">專案主題</p>
			<h2 id="phoPrjMgmt_hDate" name="phoPrjMgmt_hDate">@TempData["PjtTopic"]</h2>
			<p class="time">專案建立日期：@TempData["PjtDate"]</p>
			<p id="phoPrjMgmt_phoName" name="phoPrjMgmt_phoName">預約攝影師：@TempData["PhotoName"]</p>
			<br>
			<p id="phoPrjMgmt_pDetail" name="phoPrjMgmt_pDetail">
				拍攝日期：@TempData["FilmDate"] <br>
				拍攝開始時間：@TempData["FilmTime"]<br>
				拍攝地點：@TempData["City"] / @TempData["Loc"]<br>
				出圖張數：@TempData["PrintQty"] 張<br>
				專案預算：@TempData["Budget"] 元
			</p>
			<br>
			<p id="phoPrjMgmt_pContect" name="phoPrjMgmt_pContect">
				指定聯絡人：@TempData["Contact"]<br>
				聯絡人電話：@TempData["ContactTel"]<br>
				可聯繫時間：平日 @TempData["WkdyTime"] / 假日 @TempData["WkndTime"]
			</p>
			<br>
			<p id="phoPrjMgmt_pDescribe" name="phoPrjMgmt_pDescribe">
				其他需求描述：<br>
				@TempData["Req"]
			</p>
			<br>
			<p>參考連結：@TempData["Style"]</p>
			<p>風格參考</p>
			<div id="phoPrjMgmt_dicForImgStyle" name="phoPrjMgmt_dicForImgStyle" class="row picture">
				<div class="col"><img id="phoPrjMgmt_ImgStyle" name="phoPrjMgmt_ImgStyle" src="~/Content/@TempData["PicUpload"]" alt=""></div>
				<div class="col"><img src="" alt="" style="display:none;"></div>
				<div class="col"><img src="" alt="" style="display:none;"></div>
				<div class="col"><img src="" alt="" style="display:none;"></div>
				<div class="col"><img src="" alt="" style="display:none;"></div>
			</div>

		</div>
	</div>
</div>
<!-- #article 右側欄內容：專案內容區塊 -->
<!----------------------------------->


<!--------------------------------->
<!-- #article 右側欄內容：留言板區塊start -->
<div id="phoPrjMgmt_divForChat1" name="phoPrjMgmt_divForChat1" class="phoPrjMgmt_divForChat">
	<p>與聯絡人聊聊</p>
	<div id="phoPrjMgmt_divForText" name="phoPrjMgmt_divForText" class="phoPrjMgmt_divForText">
		<img id="phoPrjMgmt_imgPho" name="phoPrjMgmt_imgPho" src="~/Content/img/lucas-pezeta/lucas-pezeta-user.jpeg" alt="">

		@using (Html.BeginForm("Create", "PhoPrjMgmt", FormMethod.Post, new { enctype = "multipart/form-data" }))
		{
			//try
			//{
			//	string key = Request.QueryString["Key"];
			<input type="hidden" id="fixkey" name="fixkey" value="@TempData["fixkey"]" />
			@*}
			catch (Exception ex) { throw; }*@

			<input type="hidden" name="msgOrderNo" value="@TempData["OrderNum"]" />
			<textarea class="chattext" name="phoPrjMgmt_texboxChat" id="phoPrjMgmt_texboxChat" cols="80" rows="2" aria-valuemax="150" placeholder="聊聊吧..."></textarea>
			<input id="phoPrjMgmt_submChat" name="phoPrjMgmt_submChat" type="submit" value="發送" for="pmsgfix">
		}
	</div>
</div>
<br>
<br>
@{
	Html.RenderAction("_PhoMsgPartial");
}

ShootShot/Views/PhoPrjMgmt/ReplyCustMsg.cshtml
@model ShootShot.ViewModels.MProjectViewModel

@{
	ViewBag.Title = "ReplyCustMsg";
	Layout = "~/Views/Shared/_LayoutForPhotoPrj.cshtml";
}
<article>
	<div class="phoPrjMgmt_divForMain" id="phoPrjMgmt_divForMain">
		<div class="container">
			<div class="project">
			<h3 style="margin: 60px 0px 0px 0px;">回覆留言</h3>
			<form method="post" action="~/PhoPrjMgmt/ReplyCustMsg">
				<p>
					<input type="hidden" name="fId" value="@Model.msg.fId" style="margin:auto 50px;" />
					<input type="hidden" name="fCEmail" value="@Model.msg.fCEmail" style="margin:auto 50px;" />
				</p>
				<div class="mb-3">
					<label for="formGroupExampleInput" class="form-label">顧客留言</label>
					<textarea type="text" class="form-control" id="formGroupExampleInput2" maxlength="50" name="fCMsg" value="@Model.msg.fCMsg" readonly style="border-radius:15px;">@Model.msg.fCMsg</textarea>
				</div>
				<div class="mb-3">
					<label for="formGroupExampleInput2" class="form-label">您的留言</label>
					<textarea type="text" class="form-control" id="formGroupExampleInput2" placeholder="請回覆您的訊息" maxlength="50" name="fPMsg" value="@Model.msg.fPMsg" style="border-radius:15px;"></textarea>
					@*<input >*@
				</div>
				<div class="mb-3">
					<label for="formGroupExampleInput2" class="form-label">時間</label>
					<input type="datetime" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder" name="fPMsgTime" value="@DateTime.Now " readonly style="border-radius:15px;">
				</div>
				<p>
					<input type="hidden" name="fCMsgTime" value="@Model.msg.fCMsgTime" style="margin:auto 50px;" />
				</p>
				<p>
					<input type="hidden" name="fOrderNum" value="@Model.msg.fOrderNum" style="margin:auto 50px;" />
				</p>
				<p>
					<input type="hidden" name="fPEmail" value="@Model.msg.fPEmail" style="margin:auto 50px;" />
				</p>
				<p>
					<input type="hidden" name="fStates" value="@Model.msg.fStates @true" style="margin:auto 50px;" />
				</p>
				<input type="submit" value="回覆"  style="border: solid aquamarine;border-radius: 15px;background-color: aquamarine;width: 70px;height: 32px; font-size:14px;padding:3px 4px;"/>
			</form>
			</div>
		</div>
	</div>
</article>